# This is a config for E2B sandbox template.
# You can use template ID (868zp6dm4r86spmpwtkk) or template name (vibe-aii-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-aii-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-aii-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-aii-test2')

team_id = "1fa1660c-8392-4c26-86f1-0558dae85f4c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-aii-test2"
template_id = "868zp6dm4r86spmpwtkk"

# Timeout configurations (in seconds)
# Default timeout for sandbox operations
timeout = 1800  # 30 minutes
# Timeout for command execution
cmd_timeout = 600  # 10 minutes
